apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "webapp.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
