frontend:
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  commandOverride: ["/bin/sh"]
  argsOverride: ["-c", "sleep 20 && exit 1"]
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
