name: Helm Deploy with Rollback

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0

      - name: Load kubeconfig from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

      - name: Run Helm Deploy Script
        run: bash ./deploy_with_alert.sh
        continue-on-error: true

      - name: Send Rollback Email (CI)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 🚨 Helm Rollback Alert
          to: mdkhairin1999@gmail.com
          from: mdkhairin1999@gmail.com
          body: |
            Helm deployment failed and was rolled back.
            Timestamp: ${{ github.run_started_at }}
